spring:
  application:
    name: voting

  datasource:
    url: jdbc:postgresql://localhost:5432/voting_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
